...

diff --git a/XP001-resolution/image b/XP001-resolution/image
--- a/XP001-resolution/image
+++ b/XP001-resolution/image
@@ -3,7 +3,7 @@
 XP=001
 
 echo "COMMAND	: $0 take pictures"
-echo "XP	: Experiment $XP"
+echo "XP	: Experiment XP$XP"
 
 IMAGES=/var/firefuse/calibration
 GCODEFIRE=/dev/firefuse/sync/cnc/marlin/gcode.fire
@@ -22,14 +22,18 @@ function gcode() {
 }
 
 function imageAt() {
-  FILE=$IMAGES/XP$XP-$2_$1.jpg
-  echo "IMAGE	: $FILE"
   sleep 1
   gcode G0$1M400
   sleep 1
   cp /dev/firefuse/sync/cv/1/camera.jpg $FILE  # ignore first
-  cp /dev/firefuse/sync/cv/1/camera.jpg $FILE 
-  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
+
+  fir i in `seq 1 1 3`
+  do
+	  FILE=$IMAGES/XP$XP-$2.$i_$1.jpg
+	  echo "IMAGE	: $FILE"
+	  cp /dev/firefuse/sync/cv/1/camera.jpg $FILE 
+	  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
+  done
 }
 
 echo "STATUS	: taking images for calibrating pixels per mm"
@@ -38,14 +42,14 @@ sleep 3
 gcode G0Z0Y0Z0M400 "Moving to origin"
 sleep 5
 
-echoe "STATUS	: removing prior experiment results"
+echo "STATUS	: removing prior experiment results"
 rm /var/firefuse/calibration/XP$XP*.jpg
 
-for i in `seq 1 1 5`
+for i in `seq 1 1 3`
 do
 	gcode G0Z0Y0Z10M400 "Moving out of vision plane"
 	imageAt X10Y10Z0 "A$i"
 	gcode G0Z0Y0Z10M400 "Moving out of vision plane"
-	imageAt X10Y10Z1 "B$i"
+	imageAt X10Y10Z0.5 "B$i"
 done
 
